@startuml
' Copyright (c) 2026 Industrial Digital Twin Association
' SPDX-License-Identifier: CC-BY-4.0

skinparam shadowing false
skinparam ArrowColor #444444
hide footbox

actor "Recycler" as User
participant "DPP service" as DPP #FFF2CC
participant "DPP IAM" as IAM #FFF2CC
participant "AAS service" as AAS #D9EAF7

User -> DPP : Update authorized Product Condition data
DPP -> IAM : Authenticate requester
IAM --> DPP : Token with recycler role and\nDPP update authorization
DPP -> AAS : Update permitted Product Condition data
AAS -> AAS : Authorize and modify data
AAS --> DPP : Updated data
DPP -> DPP : Perform applicable DPP responsibilities
DPP --> User : Updated data
@enduml
